### ISSUE TITLE
#1 IP in .exe anzeigen

### ISSUE THREAD

**Issue by stemaa14** [stemaa14/MusicBox#1]
Beim Start der Website sollte die IP des Host-PCs angezeigt werden. Wenn die Website mit `pserve production.ini --browser` gestartet wird, wird die IP des Host-PCs als Adresse benutzt. Diese muss "User freundlich" angezeigt werden. + Instructions

**Comment by rotflb13** [comment]
[MusikBoxStartGUI.zip](https://github.com/stemaa14/MusicBox/files/824581/MusikBoxStartGUI.zip)
